import { UserType } from '@/interfaces/user.interface';

/** Actions aligned with `_data/permissions.json` (sermon streaming). */
const ALL_STREAMING_PERMISSIONS: string[] = [
    'user:create',
    'user:read',
    'user:update',
    'user:delete',
    'user:disable',
    'sermon:create',
    'sermon:read',
    'sermon:update',
    'sermon:destroy',
    'sermon:delete',
    'sermonbite:create',
    'sermonbite:read',
    'sermonbite:update',
    'sermonbite:destroy',
    'sermonbite:delete',
    'playlist:create',
    'playlist:read',
    'playlist:update',
    'playlist:destroy',
    'playlist:disable',
    'playlist:delete',
    'subscription:create',
    'subscription:read',
    'subscription:update',
    'subscription:cancel',
    'transaction:create',
    'transaction:read',
    'transaction:update',
    'transaction:refund',
    'plan:create',
    'plan:read',
    'plan:update',
    'plan:delete',
    'role:create',
    'role:read',
    'role:update',
    'role:disable',
    'role:delete',
    'permission:create',
    'permission:read',
    'permission:update',
    'permission:disable',
    'permission:delete',
    'apikey:create',
    'apikey:read',
    'apikey:update',
    'apikey:disable',
    'apikey:delete',
    'analytics:read',
    'analytics:update',
    'analytics:export',
    'revenue:read',
    'revenue:update',
    'ads:create',
    'ads:read',
    'ads:update',
    'ads:delete',
    'system:read',
    'system:update',
    'system:configure',
    'system:restart',
];

const ADMIN_STREAMING_PERMISSIONS = ALL_STREAMING_PERMISSIONS.filter(
    (p) => p !== 'system:restart',
);

const MINISTER_PERMISSIONS: string[] = [
    'user:read',
    'user:update',
    'sermon:create',
    'sermon:read',
    'sermon:update',
    'sermon:delete',
    'sermon:destroy',
    'playlist:create',
    'playlist:read',
    'playlist:update',
    'playlist:delete',
    'playlist:destroy',
    'playlist:disable',
    'sermonbite:read',
    'subscription:read',
    'subscription:create',
    'subscription:update',
    'subscription:cancel',
    'transaction:read',
    'plan:read',
    'analytics:read',
];

const CREATOR_PERMISSIONS: string[] = [
    'user:read',
    'user:update',
    'sermonbite:create',
    'sermonbite:read',
    'sermonbite:update',
    'sermonbite:delete',
    'sermonbite:destroy',
    'sermon:read',
    'playlist:read',
    'playlist:create',
    'playlist:update',
    'subscription:read',
    'subscription:create',
    'subscription:update',
    'subscription:cancel',
    'transaction:read',
    'plan:read',
];

const LISTENER_AND_APP_USER: string[] = [
    'user:read',
    'user:update',
    'sermon:read',
    'sermonbite:read',
    'playlist:read',
    'subscription:read',
    'transaction:read',
    'plan:read',
];

/**
 * Maps role names (same strings as `UserType` / `_data/roles.json` `name`) to permission actions.
 * Used during permission seeding to attach permission documents to roles.
 */
export const rolePermissionMap: Record<string, string[]> = {
    [UserType.SUPERADMIN]: [...ALL_STREAMING_PERMISSIONS],
    [UserType.ADMIN]: [...ADMIN_STREAMING_PERMISSIONS],
    [UserType.MINISTER]: [...MINISTER_PERMISSIONS],
    [UserType.CREATOR]: [...CREATOR_PERMISSIONS],
    [UserType.LISTENER]: [...LISTENER_AND_APP_USER],
    [UserType.USER]: [...LISTENER_AND_APP_USER],
};
