import { IRoute } from '@/utils/interfaces';

const workspaceRoutes: Array<IRoute> = [
    {
        name: 'workspace',
        title: 'Workspace',
        url: 'workspace',
        iconName: 'briefcase',
        action: 'navigate',
        isAuth: true,
        params: [],
        content: { collapsed: false },
        subroutes: [
            {
                name: 'my-hackathons',
                title: 'My Hackathons',
                iconName: 'trophy',
                url: '/hackathons',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                name: 'my-challenges',
                title: 'My Challenges',
                iconName: 'zap',
                url: '/challenges',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                name: 'my-projects',
                title: 'My Projects',
                iconName: 'folder',
                url: '/projects',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
        ],

        inroutes: [
            {
                route: 'workspace',
                parent: 'my-hackathons',
                name: 'create-hackathon',
                title: 'Host a Hackathon',
                url: '/hackathons/create',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-hackathons',
                name: 'hackathon-details',
                title: 'Hackathon Details',
                url: '/hackathons/:id',
                action: 'navigate',
                isAuth: true,
                params: [{ type: 'url', name: 'id' }],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-hackathons',
                name: 'edit-hackathon',
                title: 'Edit Hackathon',
                url: '/hackathons/:id/edit',
                action: 'navigate',
                isAuth: true,
                params: [{ type: 'url', name: 'id' }],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-projects',
                name: 'create-project',
                title: 'New Project',
                url: '/projects/create',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-projects',
                name: 'project-details',
                title: 'Project Details',
                url: '/projects/:id',
                action: 'navigate',
                isAuth: true,
                params: [{ type: 'url', name: 'id' }],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-projects',
                name: 'project-editor',
                title: 'Edit Project',
                url: '/projects/edit/:id',
                action: 'navigate',
                isAuth: true,
                params: [{ type: 'url', name: 'id' }],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-challenges',
                name: 'create-challenge',
                title: 'New Challenge',
                url: '/challenges/create',
                action: 'navigate',
                isAuth: true,
                params: [],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-challenges',
                name: 'challenge-details',
                title: 'Challenge Details',
                url: '/challenges/:id',
                action: 'navigate',
                isAuth: true,
                params: [{ type: 'url', name: 'id' }],
                content: { backButton: true },
            },
            {
                route: 'workspace',
                parent: 'my-challenges',
                name: 'edit-challenge',
                title: 'Edit Challenge',
                url: '/challenges/:id/edit',
                action: 'navigate',
                isAuth: true,
                params: [{ type: 'url', name: 'id' }],
                content: { backButton: true },
            },
        ],
    },
];

export default workspaceRoutes;
