import React, { useEffect, useState, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import {
  FileAudio,
  Globe,
  Lock,
  User,
  Tag,
  Calendar,
  Clock,
  Pencil,
  Trash2,
  Copy,
  ChevronUp,
  Link as LinkIcon,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { useUpload, uploadActions } from '@/context/upload/upload.context';
import apiCall from '@/api/config';
import storage from '@/utils/storage.util';

export const sermonQueryKeys = {
  all: ['sermons'] as const,
};

interface ReviewSubmitProps {
  onModalClose?: () => void;
  onSubmitRef?: React.MutableRefObject<(() => void) | null>;
}

function apiErrorMessage(err: unknown): string {
  if (
    err &&
    typeof err === 'object' &&
    'message' in err &&
    typeof (err as { message: unknown }).message === 'string'
  ) {
    return (err as { message: string }).message;
  }
  return 'Something went wrong. Please try again.';
}

const ReviewSubmit: React.FC<ReviewSubmitProps> = ({
  onModalClose,
  onSubmitRef,
}) => {
  const { state, dispatch } = useUpload();
  const { uploadData, isLoading, uploadComplete, progress } = state;
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [showMoreFields, setShowMoreFields] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);
  const [isThumbnailAutoGenerated] = useState(true);

  const isUploading =
    !!uploadData.file &&
    !uploadComplete &&
    isLoading &&
    progress > 0 &&
    progress < 100;

  const buildPublishBody = useCallback(
    (status: 'published' | 'draft') => {
      const userId = storage.getUserID();
      const release = uploadData.scheduledDate ?? new Date();

      return {
        title: uploadData.title,
        description: uploadData.description,
        topic: uploadData.category || '',
        tags: uploadData.tags ?? [],
        isPublic: uploadData.isPublic ?? true,
        minister: userId,
        publishedBy: userId,
        size: uploadData.file?.size ?? 0,
        duration: 0,
        releaseDate: release.toISOString(),
        releaseYear: release.getFullYear(),
        state: 'active',
        status,
      } as Record<string, unknown>;
    },
    [uploadData]
  );

  const handleSubmit = useCallback(async () => {
    const sermonId = uploadData.sermonId;
    if (!sermonId) {
      toast.error('Upload is not complete. Please finish audio upload first.');
      return;
    }

    dispatch(uploadActions.setLoading(true));
    try {
      await apiCall.sermon.publishSermon(
        sermonId,
        buildPublishBody('published')
      );
      queryClient.invalidateQueries({ queryKey: sermonQueryKeys.all });
      dispatch(uploadActions.resetUpload());
      onModalClose?.();
      navigate('/get-sermons');
      toast.success('Sermon published successfully', {
        description: 'Your sermon metadata has been saved.',
      });
    } catch (e) {
      toast.error(apiErrorMessage(e));
    } finally {
      dispatch(uploadActions.setLoading(false));
    }
  }, [
    dispatch,
    uploadData.sermonId,
    buildPublishBody,
    onModalClose,
    navigate,
    queryClient,
  ]);

  useEffect(() => {
    if (onSubmitRef) {
      onSubmitRef.current = () => {
        void handleSubmit();
      };
    }
    return () => {
      if (onSubmitRef) {
        onSubmitRef.current = null;
      }
    };
  }, [onSubmitRef, handleSubmit]);

  const handleSaveDraft = async () => {
    const sermonId = uploadData.sermonId;
    if (!sermonId) {
      toast.error('Upload audio first before saving a draft.');
      return;
    }

    dispatch(uploadActions.setLoading(true));
    try {
      await apiCall.sermon.publishSermon(
        sermonId,
        buildPublishBody('draft')
      );
      queryClient.invalidateQueries({ queryKey: sermonQueryKeys.all });
      dispatch(uploadActions.resetUpload());
      onModalClose?.();
      navigate('/get-sermons');
      toast.success('Sermon saved to drafts', {
        description: 'You can continue editing and publish it later.',
      });
    } catch (e) {
      toast.error(apiErrorMessage(e));
    } finally {
      dispatch(uploadActions.setLoading(false));
    }
  };

  const generateSermonLink = () => {
    if (uploadComplete && uploadData.sermonId) {
      const origin =
        typeof window !== 'undefined' ? window.location.origin : '';
      return `${origin}/sermons/${uploadData.sermonId}`;
    }
    return '';
  };

  const handleCopyLink = async () => {
    const link = generateSermonLink();
    if (!link) return;
    try {
      await navigator.clipboard.writeText(link);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
    } catch {
      toast.error('Could not copy link.');
    }
  };

  const handleEditFile = () => {
    dispatch(uploadActions.setStep('progress'));
  };

  const handleDeleteFile = () => {
    dispatch(uploadActions.setFile(null));
    dispatch(uploadActions.setProgress(0));
    dispatch(uploadActions.setUploadComplete(false));
  };

  const handleEditTitle = () => {
    dispatch(uploadActions.setStep('details'));
  };

  const handleEditDescription = () => {
    dispatch(uploadActions.setStep('details'));
  };

  const handleEditThumbnail = () => {
    dispatch(uploadActions.setStep('details'));
  };

  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-4 h-full">
      <div className="space-y-4 overflow-y-auto scrollbar-none max-h-[calc(100vh-150px)] pr-2">
        <div className="flex flex-wrap items-center justify-between gap-2 border border-border/50 rounded-lg p-3 bg-muted/20">
          <p className="text-sm text-muted-foreground">
            {isUploading
              ? 'Audio is still uploading. Publish becomes available when upload finishes.'
              : uploadComplete
                ? 'Audio is ready. Add details below, then use Publish in the footer.'
                : 'Waiting for upload status.'}
          </p>
          <div className="flex gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              disabled={isLoading || isUploading}
              onClick={() => void handleSaveDraft()}
            >
              Save as draft
            </Button>
          </div>
        </div>

        {uploadData.file && (
          <div className="border border-border/50 rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3 flex-1 min-w-0">
                <FileAudio className="h-5 w-5 text-muted-foreground flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-foreground truncate">
                    {uploadData.file.name}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    {formatFileSize(uploadData.file.size)}
                    {uploadComplete ? ' — Ready' : ' — Uploading'}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleEditFile}
                  className="h-8 w-8 p-0"
                >
                  <Pencil className="h-4 w-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDeleteFile}
                  className="h-8 w-8 p-0 text-destructive hover:text-destructive"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        )}

        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <Label className="text-sm font-medium">Title (required)</Label>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleEditTitle}
              className="h-6 w-6 p-0"
            >
              <Pencil className="h-3 w-3" />
            </Button>
          </div>
          <p className="text-foreground">
            {uploadData.title || 'No title provided'}
          </p>
        </div>

        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <Label className="text-sm font-medium">Description (required)</Label>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleEditDescription}
              className="h-6 w-6 p-0"
            >
              <Pencil className="h-3 w-3" />
            </Button>
          </div>
          <p className="text-foreground text-sm line-clamp-3">
            {uploadData.description || 'No description provided'}
          </p>
        </div>

        <div className="space-y-2 border border-border/50 rounded-lg p-4">
          <Label className="text-sm font-medium">Summary</Label>
          <div className="flex flex-wrap gap-2 text-sm text-muted-foreground">
            <Badge variant="secondary" className="gap-1">
              <User className="h-3 w-3" />
              Category: {uploadData.category || '—'}
            </Badge>
            {uploadData.tags?.length ? (
              uploadData.tags.map((tag) => (
                <Badge key={tag} variant="outline" className="gap-1">
                  <Tag className="h-3 w-3" />
                  {tag}
                </Badge>
              ))
            ) : (
              <span>No tags</span>
            )}
            <Badge variant="secondary" className="gap-1">
              {uploadData.isPublic ? (
                <Globe className="h-3 w-3" />
              ) : (
                <Lock className="h-3 w-3" />
              )}
              {uploadData.isPublic === undefined
                ? 'Visibility not set'
                : uploadData.isPublic
                  ? 'Public'
                  : 'Not public'}
            </Badge>
            {uploadData.scheduledDate ? (
              <Badge variant="secondary" className="gap-1">
                <Calendar className="h-3 w-3" />
                {uploadData.scheduledDate.toLocaleString()}
              </Badge>
            ) : (
              <Badge variant="secondary" className="gap-1">
                <Clock className="h-3 w-3" />
                Publish immediately
              </Badge>
            )}
          </div>
        </div>

        {uploadComplete && generateSermonLink() && (
          <div className="space-y-2">
            <Label className="text-sm font-medium">Link</Label>
            <div className="flex items-center gap-2">
              <div className="flex-1 flex items-center gap-2 px-3 py-2 bg-muted rounded-md min-w-0">
                <LinkIcon className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                <span className="text-sm text-blue-600 truncate">
                  {generateSermonLink()}
                </span>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => void handleCopyLink()}
                className="h-8 w-8 p-0 flex-shrink-0"
              >
                <Copy className="h-4 w-4" />
              </Button>
            </div>
            {linkCopied && (
              <p className="text-xs text-green-600">Link copied.</p>
            )}
          </div>
        )}

        {!showMoreFields && (
          <Button
            type="button"
            onClick={() => setShowMoreFields(true)}
            className="bg-[#707070] cursor-pointer hover:bg-[#404040] text-[#EAEAEA] rounded-full border-0"
          >
            <ChevronUp className="h-4 w-4 mr-2" />
            Show more
          </Button>
        )}
      </div>

      <div className="space-y-3 lg:sticky lg:top-0 lg:h-fit">
        <div className="space-y-2">
          <div className="mb-2">
            <Label>Thumbnail</Label>
            <div className="text-sm text-muted-foreground mb-2">
              Set a thumbnail that stands out and draws listeners in.
            </div>
          </div>

          {uploadData.thumbnailPreview ? (
            <div className="relative w-full min-h-[200px]" style={{ aspectRatio: '4/3' }}>
              <div className="relative w-full h-full rounded-lg overflow-hidden border border-border/50">
                <img
                  src={uploadData.thumbnailPreview}
                  alt="Sermon thumbnail"
                  className="w-full h-full object-cover"
                />
                {isThumbnailAutoGenerated && (
                  <div className="absolute bottom-2 left-2 flex items-center gap-1 bg-white/90 backdrop-blur-sm px-2 py-1 rounded text-xs font-medium">
                    <FileAudio className="h-3 w-3" />
                    <span>From file</span>
                  </div>
                )}
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleEditThumbnail}
                  className="absolute top-2 right-2 bg-background/80 backdrop-blur-sm hover:bg-background/90 h-8 w-8 p-0"
                >
                  <Pencil className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ) : (
            <div className="border-2 border-dashed rounded-lg p-8 text-center w-full min-h-[200px] flex items-center justify-center">
              <p className="text-sm text-muted-foreground">No thumbnail</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReviewSubmit;
