import Listener from './Listener.model';
import { MediaSourceType, RepeatMode } from './Playback.model';

interface Queue {
    code: string;

    // Relationships
    listener: Listener | any;

    // Items
    items: Array<QueueItem>;
    currentIndex: number;

    // Queue Behavior
    shuffle: boolean;
    repeatMode: RepeatMode;

    sourceType: MediaSourceType;
    sourceId: string;

    // Queue behavior
    autoGenerated: boolean;
    locked: boolean;

    // time stamps
    createdAt: string;
    updatedAt: string;
    _version: number;
    _id: string;
    id: string;
}

export interface QueueItem {
    id: string; // the id of the queue item

    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string; // the id of the source of the media item eg. sermon id, series id, playlist id

    position: number;
    addedAt: string;
    addedBy: QueueItemSourceType; // the source of the media item eg. listener, system, recommendation
}

export enum QueueItemSourceType {
    LISTENER = 'listener',
    SYSTEM = 'system',
    RECOMMENDATION = 'recommendation',
}

export enum MediaType {
    SERMON = 'sermon',
    SERIES = 'series',
    PLAYLIST = 'playlist',
}

export default Queue;
