import React, { useEffect, useState, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { FileAudio, Clock, Globe, Lock, User, Tag, Calendar, Pencil, Trash2, Copy, ChevronUp, Link as LinkIcon, CheckCircle2, ArrowUp } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { useUpload, uploadActions } from '@/context/upload/upload.context';
import { useDraft } from '@/context/draft/draft.context';

interface ReviewSubmitProps {
  onModalClose?: () => void;
  onSubmitRef?: React.MutableRefObject<(() => void) | null>;
  onSaveDraftRef?: React.MutableRefObject<(() => Promise<void>) | null>;
}

const ReviewSubmit: React.FC<ReviewSubmitProps> = ({ onModalClose, onSubmitRef, onSaveDraftRef }) => {
  const { state, dispatch } = useUpload();
  const { saveDraft, updateDraft } = useDraft();
  const { uploadData, isLoading, uploadComplete, progress } = state;
  const navigate = useNavigate();
  const [showMoreFields, setShowMoreFields] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);
  const [isThumbnailAutoGenerated] = useState(true); // You can make this dynamic based on your logic
  const [autoSaveDone, setAutoSaveDone] = useState(false);
  
  // Check if upload is in progress
  const isUploading = uploadData.file && !uploadComplete && isLoading && progress > 0 && progress < 100;

  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  // Auto-save draft silently (called when upload completes)
  const handleAutoSaveDraft = useCallback(async () => {
    try {
      if (uploadData.draftId) {
        await updateDraft(uploadData.draftId, {
          title: uploadData.title,
          description: uploadData.description,
          tags: uploadData.tags,
          category: uploadData.category,
          isPublic: uploadData.isPublic,
          scheduledDate: uploadData.scheduledDate,
          seriesId: uploadData.seriesId,
        });
      } else {
        const newDraft = await saveDraft({
          title: uploadData.title,
          description: uploadData.description,
          tags: uploadData.tags,
          category: uploadData.category,
          isPublic: uploadData.isPublic,
          scheduledDate: uploadData.scheduledDate,
          seriesId: uploadData.seriesId,
        });
        // Update the upload context with the new draft ID
        dispatch(uploadActions.setUploadData({ draftId: newDraft.draftId }));
      }
      // Silent save - no toast notification
    } catch (error: any) {
      // Silently fail for auto-save - user can manually save if needed
      console.error('Auto-save draft failed:', error);
    }
  }, [uploadData, saveDraft, updateDraft, dispatch]);

  const handleSubmit = useCallback(() => {
    // If upload is not complete, save as draft instead
    if (!uploadComplete) {
      handleSaveDraft();
      return;
    }

    dispatch(uploadActions.setLoading(true));
    // Here you would typically submit the sermon data to your API
    console.log('Submitting sermon:', uploadData);
    
    // Simulate API call
    setTimeout(() => {
      dispatch(uploadActions.setLoading(false));
      // Close modal and navigate to My Sermons
      onModalClose?.();
      navigate('/get-sermons');
      // Show success toast
      toast.success('Sermon published successfully', {
        description: 'Your sermon is now live and available to your audience.',
      });
    }, 2000);
  }, [dispatch, uploadData, uploadComplete, onModalClose, navigate]);

  // Expose submit handler to parent component
  useEffect(() => {
    if (onSubmitRef) {
      onSubmitRef.current = handleSubmit;
    }
    return () => {
      if (onSubmitRef) {
        onSubmitRef.current = null;
      }
    };
  }, [onSubmitRef, handleSubmit]);

  // Expose save draft handler to parent component
  useEffect(() => {
    if (onSaveDraftRef) {
      onSaveDraftRef.current = handleSaveDraft;
    }
    return () => {
      if (onSaveDraftRef) {
        onSaveDraftRef.current = null;
      }
    };
  }, [onSaveDraftRef, handleSaveDraft]);

  // Clear any previous loading states when component mounts
  useEffect(() => {
    dispatch(uploadActions.setLoading(false));
  }, [dispatch]);

  // Auto-save to draft when upload completes (silent, no navigation)
  useEffect(() => {
    if (uploadComplete && !autoSaveDone && uploadData.title && uploadData.description) {
      setAutoSaveDone(true);
      handleAutoSaveDraft();
    }
  }, [uploadComplete, autoSaveDone, handleAutoSaveDraft]);

  const handleSaveDraft = useCallback(async () => {
    dispatch(uploadActions.setLoading(true));
    try {
      // If draftId exists, update the draft; otherwise, create a new one
      if (uploadData.draftId) {
        await updateDraft(uploadData.draftId, {
          title: uploadData.title,
          description: uploadData.description,
          tags: uploadData.tags,
          category: uploadData.category,
          isPublic: uploadData.isPublic,
          scheduledDate: uploadData.scheduledDate,
          seriesId: uploadData.seriesId,
        });
        toast.success('Draft updated', {
          description: 'Your sermon draft has been saved.',
        });
      } else {
        const newDraft = await saveDraft({
          title: uploadData.title,
          description: uploadData.description,
          tags: uploadData.tags,
          category: uploadData.category,
          isPublic: uploadData.isPublic,
          scheduledDate: uploadData.scheduledDate,
          seriesId: uploadData.seriesId,
        });
        // Update the upload context with the new draft ID
        dispatch(uploadActions.setUploadData({ draftId: newDraft.draftId }));
        toast.success('Draft saved', {
          description: 'You can continue editing and publish it later.',
        });
      }
      dispatch(uploadActions.setLoading(false));
      onModalClose?.();
      navigate('/get-sermons');
    } catch (error: any) {
      dispatch(uploadActions.setLoading(false));
      toast.error('Failed to save draft', {
        description: error?.message || 'Please try again.',
      });
    }
  }, [uploadData, saveDraft, updateDraft, dispatch, onModalClose, navigate]);

  const generateSermonLink = () => {
    if (uploadComplete && uploadData.sermonId) {
      return `https://troott.be/${uploadData.sermonId}`;
    }
    // Generate a random link for preview
    return `https://troott.be/dcXlvoEauNU`;
  };

  const handleCopyLink = async () => {
    const link = generateSermonLink();
    if (link) {
      try {
        await navigator.clipboard.writeText(link);
        setLinkCopied(true);
        setTimeout(() => setLinkCopied(false), 2000);
      } catch (err) {
        console.error('Failed to copy link:', err);
      }
    }
  };

  const handleEditFile = () => {
    dispatch(uploadActions.setStep('progress'));
  };

  const handleDeleteFile = () => {
    dispatch(uploadActions.setFile(null));
    dispatch(uploadActions.setProgress(0));
    dispatch(uploadActions.setUploadComplete(false));
  };

  const handleEditTitle = () => {
    dispatch(uploadActions.setStep('details'));
  };

  const handleEditDescription = () => {
    dispatch(uploadActions.setStep('details'));
  };

  const handleEditThumbnail = () => {
    dispatch(uploadActions.setStep('details'));
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-4 h-full">
      {/* Left Column - Content Details */}
      <div className="space-y-4 overflow-y-auto scrollbar-none max-h-[calc(100vh-150px)] pr-2">
        {/* File Information */}
        {uploadData.file && (
          <div className="border border-border/50 rounded-lg p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3 flex-1 min-w-0">
                <FileAudio className="h-5 w-5 text-muted-foreground flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-foreground truncate">{uploadData.file.name}</p>
                  <p className="text-sm text-muted-foreground">
                    {formatFileSize(uploadData.file.size)} • Ready for upload
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleEditFile}
                  className="h-8 w-8 p-0"
                >
                  <Pencil className="h-4 w-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleDeleteFile}
                  className="h-8 w-8 p-0 text-destructive hover:text-destructive"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Title */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <Label className="text-sm font-medium">Title (required)</Label>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleEditTitle}
              className="h-6 w-6 p-0"
            >
              <Pencil className="h-3 w-3" />
            </Button>
          </div>
          <p className="text-foreground">{uploadData.title || 'No title provided'}</p>
        </div>

        {/* Description */}
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <Label className="text-sm font-medium">Description (required)</Label>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleEditDescription}
              className="h-6 w-6 p-0"
            >
              <Pencil className="h-3 w-3" />
            </Button>
          </div>
          <p className="text-foreground text-sm line-clamp-3">
            {uploadData.description || 'No description provided'}
          </p>
        </div>

        {/* Link */}
        {uploadComplete && (
          <div className="space-y-2">
            <Label className="text-sm font-medium">Link</Label>
            <div className="flex items-center gap-2">
              <div className="flex-1 flex items-center gap-2 px-3 py-2 bg-muted rounded-md">
                <LinkIcon className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                <span className="text-sm text-blue-600 truncate">{generateSermonLink()}</span>
              </div>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopyLink}
                className="h-8 w-8 p-0 flex-shrink-0"
              >
                <Copy className="h-4 w-4" />
              </Button>
            </div>
            {linkCopied && (
              <p className="text-xs text-green-600">Link copied!</p>
            )}
          </div>
        )}

        {/* Show More Button */}
        {!showMoreFields && (
          <Button
            type="button"
            onClick={() => setShowMoreFields(true)}
            className="bg-[#707070] cursor-pointer hover:bg-[#404040] text-[#EAEAEA] rounded-full border-0"
          >
            <ChevronUp className="h-4 w-4 mr-2" />
            Show more
          </Button>
        )}
      </div>

      {/* Right Column - Thumbnail */}
      <div className="space-y-3 lg:sticky lg:top-0 lg:h-fit">
        <div className="space-y-2">
          <div className="mb-2">
            <Label>Thumbnail (required)</Label>
            <div className="text-sm text-muted-foreground mb-2">
              Set a thumbnail that stands out and draws viewers' attention.
            </div>
          </div>
          
          {uploadData.thumbnailPreview ? (
            <div className="relative w-full" style={{ minHeight: '200px', aspectRatio: '4/3' }}>
              <div className="relative w-full h-full rounded-lg overflow-hidden border border-border/50">
                <img 
                  src={uploadData.thumbnailPreview} 
                  alt="Sermon thumbnail" 
                  className="w-full h-full object-cover"
                />
                
                {/* Auto-generated Overlay */}
                {isThumbnailAutoGenerated && (
                  <div className="absolute bottom-2 left-2 flex items-center gap-1 bg-white/90 backdrop-blur-sm px-2 py-1 rounded text-xs font-medium">
                    <FileAudio className="h-3 w-3" />
                    <span>Auto-generated</span>
                  </div>
                )}
                
                {/* Edit Button */}
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleEditThumbnail}
                  className="absolute top-2 right-2 bg-background/80 backdrop-blur-sm hover:bg-background/90 h-8 w-8 p-0"
                >
                  <Pencil className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ) : (
            <div className="border-2 border-dashed rounded-lg p-8 text-center w-full min-h-[200px] flex items-center justify-center">
              <p className="text-sm text-muted-foreground">No thumbnail</p>
            </div>
          )}
        </div>
      </div>

      {/* Action Buttons - These will be in the footer of the modal */}
      {/* Upload Status - This will be shown in the footer of the modal */}
    </div>
  );
};

export default ReviewSubmit;