import mongoose, { Schema, Model } from 'mongoose';
import type IQueueDoc from '@/interfaces/core/queue.interface';
import { QueueItemSourceType } from '@/interfaces/core/queue.interface';
import {
    RepeatMode,
    MediaSourceType,
} from '@/interfaces/core/playback.interface';
import { DbModels } from '@/types/common.enum';

const QueueSchema = new Schema<IQueueDoc>(
    {
        code: { type: String, unique: true, sparse: true, index: true },

        listener: {
            type: Schema.Types.ObjectId,
            ref: DbModels.LISTENER,
            required: true,
            index: true,
        },

        items: [
            {
                id: { type: String },
                mediaId: { type: String, required: true },
                sourceType: {
                    type: String,
                    enum: Object.values(MediaSourceType),
                },
                sourceId: { type: String },
                position: { type: Number },
                addedAt: { type: String },
                addedBy: {
                    type: String,
                    enum: Object.values(QueueItemSourceType),
                },
            },
        ],
        currentIndex: { type: Number, default: 0 },

        shuffle: { type: Boolean, default: false },
        repeatMode: {
            type: String,
            enum: Object.values(RepeatMode),
            default: RepeatMode.OFF,
        },

        sourceType: {
            type: String,
            enum: Object.values(MediaSourceType),
            required: true,
            index: true,
        },
        sourceId: { type: String, required: true },

        autoGenerated: { type: Boolean, default: false },
        locked: { type: Boolean, default: false },
    },
    {
        timestamps: true,
        versionKey: '_version',
        toJSON: {
            virtuals: true,
            getters: true,
            transform(_doc: any, ret) {
                ret.id = ret._id;
                delete (ret as any).__v;
                return ret;
            },
        },
    },
);

QueueSchema.index({ listener: 1 });

const Queue: Model<IQueueDoc> = mongoose.model<IQueueDoc>(
    DbModels.QUEUE,
    QueueSchema,
);

export default Queue;
