/** Shared reducer action type strings for app and user context slices. */

export const GET_LOGGEDIN_USER = 'GET_LOGGEDIN_USER';
export const GET_LISTENER = 'GET_LISTENER';
export const SET_USER = 'SET_USER';
export const SET_USERTYPE = 'SET_USERTYPE';
export const SET_LISTENER = 'SET_LISTENER';
export const SET_LISTENER_ONBOARDING = 'SET_LISTENER_ONBOARDING';
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADER = 'SET_LOADER';
export const UNSET_LOADING = 'UNSET_LOADING';
export const SET_IS_FIRST_TIME_USER = 'SET_IS_FIRST_TIME_USER';

// Auth form slices (register + forgot password)
export const REGISTER_SET_EMAIL = 'REGISTER_SET_EMAIL';
export const REGISTER_SET_USER_EMAIL = 'REGISTER_SET_USER_EMAIL';
export const REGISTER_SET_FIELD = 'REGISTER_SET_FIELD';
export const REGISTER_SET_TOUCHED = 'REGISTER_SET_TOUCHED';
export const REGISTER_TOGGLE_PASSWORD = 'REGISTER_TOGGLE_PASSWORD';
export const REGISTER_SET_PASSWORD_STRENGTH = 'REGISTER_SET_PASSWORD_STRENGTH';
export const REGISTER_RESET = 'REGISTER_RESET';

export const FORGOT_SET_STEP = 'FORGOT_SET_STEP';
export const FORGOT_SET_FORM_DATA = 'FORGOT_SET_FORM_DATA';
export const FORGOT_SET_ERRORS = 'FORGOT_SET_ERRORS';
export const FORGOT_SET_TOUCHED = 'FORGOT_SET_TOUCHED';
export const FORGOT_SET_RESEND_COUNTDOWN = 'FORGOT_SET_RESEND_COUNTDOWN';
export const FORGOT_RESET = 'FORGOT_RESET';
