import { Document, Types } from 'mongoose';
import IListenerDoc from './listener.interface';
import IMinisterDoc from './minister.interface';
import ISeriesDoc from './series.interface';
import ISermonDoc from './sermon.interface';
import IUserDoc from './user.interface';

type ObjectId = Types.ObjectId;

/**
 * Mongoose document for a playlist.
 *
 * Playlists are ordered collections of {@link ISermonDoc sermons} and/or
 * {@link ISeriesDoc series}. They can be created by listeners, ministers,
 * or the system (e.g. algorithmic recommendations). Collaborative
 * playlists allow multiple users to add items.
 */
interface IPlaylistDoc extends Document {
    /** Short unique code. */
    code: string;
    /** URL-safe slug. */
    slug: string;

    /** Playlist title. */
    title: string;
    /** Description. */
    description: string;
    /** CDN URL of the playlist cover image. */
    banner: string;

    /** Ordered items in the playlist. */
    items: Array<PlaylistItem>;
    /** Cached count of items. */
    itemsCount: number;
    /** Sum of all item durations in milliseconds. */
    totalDurationMs: number;

    /** Lifecycle status. */
    status: PlaylistStatus;
    /** Who can see this playlist. */
    visibility: PlaylistVisibility;
    /** What kind of playlist (minister-curated, listener-created, system-generated, recommendation). */
    playlistType: PlaylistType;

    /** Role of the playlist owner. */
    ownerType: PlaylistOwnerType;
    /** Owner reference (system admin or super admin). */
    owner: IUserDoc | any;
    /** Listener owner, if applicable. */
    listener: IListenerDoc | any;
    /** Minister owner, if applicable. */
    minister: IMinisterDoc | any;

    /** Whether multiple users can add items. */
    isCollaborative: boolean;
    /** Users who can edit this playlist. */
    collaborators: Array<IUserDoc | any>;

    /** Number of likes. */
    likesCount: number;
    /** Number of saves to library. */
    savesCount: number;
    /** Number of followers. */
    followersCount: number;
    /** Number of shares. */
    sharesCount: number;
    /** Number of plays. */
    playsCount: number;

    /** Whether the playlist is publicly accessible. */
    isPublic: boolean;
    /** Whether the platform has featured this playlist. */
    isFeatured: boolean;
    /** Whether the owner has pinned this playlist. */
    isPinned: boolean;

    /** Free-form tags for search and discovery. */
    tags: Array<string>;
    /** Genre classifications. */
    genres: Array<string>;
    /** ISO-639 language codes. */
    languages: Array<string>;

    /** The user who owns this playlist (legacy field). */
    user: IUserDoc | any;
    /** The user who created this playlist. */
    createdBy: IUserDoc | any;

    /** ISO-8601 creation timestamp. */
    createdAt: string;
    /** ISO-8601 last-update timestamp. */
    updatedAt: string;
    /** Optimistic concurrency version. */
    _version: number;
    /** MongoDB ObjectId. */
    _id: ObjectId;
    /** Virtual `id` getter. */
    id: ObjectId;
}

/** A single entry in a playlist's item list. */
export interface PlaylistItem {
    /** The sermon or series document. */
    item: ISermonDoc | ISeriesDoc | any;
    /** Zero-based position within the playlist. */
    position: number;
    /** ISO-8601 timestamp when the item was added. */
    addedAt: string;
    /** User who added the item. */
    addedBy: IUserDoc | any;
}

/** Who created the playlist. */
export enum PlaylistType {
    /** Curated by a minister. */
    MINISTER = 'minister',
    /** Created by a listener. */
    LISTENER = 'listener',
    /** Generated by the platform. */
    SYSTEM = 'system',
    /** Algorithmically recommended. */
    RECOMMENDATION = 'recommendation',
}

/** Role of the playlist owner. */
export enum PlaylistOwnerType {
    LISTENER = 'listener',
    MINISTER = 'minister',
    SYSTEM = 'system',
}

/** Visibility scope of a playlist. */
export enum PlaylistVisibility {
    /** Visible to everyone. */
    PUBLIC = 'public',
    /** Visible only to the owner. */
    PRIVATE = 'private',
    /** Accessible via direct link but not listed in search. */
    UNLISTED = 'unlisted',
}

/** Lifecycle status of a playlist. */
export enum PlaylistStatus {
    ACTIVE = 'active',
    ARCHIVED = 'archived',
    DELETED = 'deleted',
}

export default IPlaylistDoc;
