import { Document, Types } from 'mongoose';
import IListenerDoc from './listener.interface';
import { MediaSourceType, RepeatMode } from './playback.interface';

type ObjectId = Types.ObjectId;

/**
 * Mongoose document for a playback queue.
 *
 * A queue is an ordered list of media items that the player works
 * through sequentially. It is created when a listener starts playback
 * from a playlist, series, or other collection, and can be manipulated
 * in real time (reorder, add, remove, shuffle).
 *
 * Referenced by {@link IPlaybackSessionDoc.queueRef}.
 */
interface IQueueDoc extends Document {
    /** Short unique code. */
    code: string;

    /** The listener who owns this queue. */
    listener: IListenerDoc | any;

    /** Ordered items in the queue. */
    items: Array<QueueItem>;
    /** Zero-based index of the currently playing item. */
    currentIndex: number;

    /** Whether shuffle mode is active. */
    shuffle: boolean;
    /** Repeat behaviour for the queue. */
    repeatMode: RepeatMode;

    /** Surface that originally populated the queue (e.g. playlist, series, search). */
    sourceType: MediaSourceType;
    /** ID of the source resource. */
    sourceId: string;

    /** Whether the queue was system-generated (e.g. auto-play / radio). */
    autoGenerated: boolean;
    /** Whether the queue is locked from user edits (e.g. ad-supported free tier). */
    locked: boolean;

    /** ISO-8601 creation timestamp. */
    createdAt: string;
    /** ISO-8601 last-update timestamp. */
    updatedAt: string;
    /** Optimistic concurrency version. */
    _version: number;
    /** MongoDB ObjectId. */
    _id: ObjectId;
    /** Virtual `id` getter. */
    id: ObjectId;
}

/** A single entry in the playback queue. */
export interface QueueItem {
    /** Unique queue item identifier. */
    id: string;

    /** Media document ID (sermon / series / playlist). */
    mediaId: string;
    /** Type of the source collection. */
    sourceType: MediaSourceType;
    /** ID of the source collection. */
    sourceId: string;

    /** Zero-based position within the queue. */
    position: number;
    /** ISO-8601 timestamp when the item was added. */
    addedAt: string;
    /** Who or what added this item to the queue. */
    addedBy: QueueItemSourceType;
}

/** Who or what added an item to the queue. */
export enum QueueItemSourceType {
    /** Listener manually added the item. */
    LISTENER = 'listener',
    /** System added the item (e.g. auto-play). */
    SYSTEM = 'system',
    /** Recommendation engine added the item. */
    RECOMMENDATION = 'recommendation',
}

/** Discriminator for media types that can appear in a queue. */
export enum MediaType {
    SERMON = 'sermon',
    SERIES = 'series',
    PLAYLIST = 'playlist',
}

export default IQueueDoc;
