/**
 * Queue DTOs aligned with `apps/api/src/dtos/core/queue.dto.ts`.
 * Enums mirror `apps/api/src/interfaces/core/queue.interface.ts`.
 */
import type {
    MediaSourceType,
    RepeatMode,
} from '@/models/Playback.model';

/** Who or what added an item to the queue (API `QueueItemSourceType`). */
export enum QueueItemSourceType {
    LISTENER = 'listener',
    SYSTEM = 'system',
    RECOMMENDATION = 'recommendation',
}

export interface CreateQueueDTO {
    items: Array<CreateQueueItemDTO>;
    sourceType: MediaSourceType;
    sourceId: string;
    shuffle?: boolean;
    repeatMode?: RepeatMode;
    startIndex?: number;
}

export interface CreateQueueItemDTO {
    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string;
    addedBy?: QueueItemSourceType;
}

export interface AddQueueItemDTO {
    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string;
    position?: number;
    addedBy?: QueueItemSourceType;
}

export interface RemoveQueueItemDTO {
    itemId: string;
}

export interface ReorderQueueDTO {
    itemId: string;
    newPosition: number;
}

export interface UpdateQueueDTO {
    currentIndex?: number;
    shuffle?: boolean;
    repeatMode?: RepeatMode;
}

export interface QueueItemResponseDTO {
    id: string;
    mediaId: string;
    sourceType: MediaSourceType;
    sourceId: string;
    position: number;
    addedAt: string;
    addedBy: QueueItemSourceType;
}

export interface QueueResponseDTO {
    id: string;
    code: string;
    items: QueueItemResponseDTO[];
    currentIndex: number;
    shuffle: boolean;
    repeatMode: RepeatMode;
    sourceType: MediaSourceType;
    sourceId: string;
    autoGenerated: boolean;
    locked: boolean;
    createdAt: string;
    updatedAt: string;
}
