export enum DbModels {
    USER = 'user',
    ROLE = 'role',
    PERMISSION = 'permission',
    NOTIFICATION = 'notification',
    APIKEY = 'ApiKey',
    BITE = 'bite',
    CATALOG = 'catalog',
    CREATOR = 'creator',
    LIBRARY = 'library',
    LISTENER = 'listener',
    PLAN = 'plan',
    PLAYLIST = 'playlist',
    MINISTER = 'Minister',
    SUBSCRIPTION = 'subscription',
    SUBSCRIPTION_INTENT = 'subscriptionIntent',
    SERIES = 'series',
    SERMON = 'sermon',
    ADMIN = 'Admin',
    TRANSACTION = 'transaction',
    UPLOAD = 'upload',
    INVITES = 'invites',
    SHAREABLE_LINK = 'shareableLink',
    USER_PREFERENCES = 'userPreferences',
    PLAYBACK_PROGRESS = 'playbackProgress',
    PUSH_DEVICE = 'pushDevice',
}
